# -*- coding: utf-8 -*-
"""life_expectancy_gdp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MI7MBFRLrdiQ4b0QXvre6o-dUdtix00s

# Introduction

For this project, you will act as a data researcher for the World Health Organization. You will investigate if there is a strong correlation between the economic output of a country and the life expectancy of its citizens.  

During this project, you will analyze, prepare, and plot data, and seek to answer questions in a meaningful way.

After you perform analysis, you'll be creating an article with your visualizations to be featured in the fictional "Time Magazine".

**Focusing Questions**: 
+ Has life expectancy increased over time in the six nations?
+ Has GDP increased over time in the six nations?
+ Is there a correlation between GDP and life expectancy of a country?
+ What is the average life expactancy in these nations?
+ What is the distribution of that life expectancy?

GDP Source:[World Bank](https://data.worldbank.org/indicator/NY.GDP.MKTP.CD)national accounts data, and OECD National Accounts data files.

Life expectancy Data Source: [World Health Organization](http://apps.who.int/gho/data/node.main.688)

## Step 1. Import Python Modules

Import the modules that you'll be using in this project:
- `from matplotlib import pyplot as plt`
- `import pandas as pd`
- `import seaborn as sns`
"""

from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns

"""## Step 2 Prep The Data

To look for connections between GDP and life expectancy you will need to load the datasets into DataFrames so that they can be visualized.

Load **all_data.csv** into a DataFrame called `df`. Then, quickly inspect the DataFrame using `.head()`.

Hint: Use `pd.read_csv()`
"""

df = pd.read_csv('all_data.csv')
df.head()

"""## Step 3 Examine The Data

The datasets are large and it may be easier to view the entire dataset locally on your computer. You can open the CSV files directly from the folder you downloaded for this project.

Let's learn more about our data:
- GDP stands for **G**ross **D**omestic **P**roduct. GDP is a monetary measure of the market value of all final goods and services produced in a time period. 
- The GDP values are in current US dollars.

What six countries are represented in the data?
"""

df['Country'].unique()

"""What years are represented in the data?"""

df['Year'].unique()

"""## Step 4 Tweak The DataFrame

Look at the column names of the DataFrame `df` using `.head()`.
"""

df.head()

"""What do you notice? The first two column names are one word each, and the third is five words long! `Life expectancy at birth (years)` is descriptive, which will be good for labeling the axis, but a little difficult to wrangle for coding the plot itself. 

**Revise The DataFrame Part A:** 

Use Pandas to change the name of the last column to `LEABY`.

Hint: Use `.rename()`. [You can read the documentation here.](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.rename.html)). </font>
"""

df.rename(columns={
    'Life expectancy at birth (years)':'LEABY'
}, inplace=True)

"""Run `df.head()` again to check your new column name worked."""

df.head()

"""---

## Step 5 Bar Charts To Compare Average

To take a first high level look at both datasets, create a bar chart for each DataFrame:

A) Create a bar chart from the data in `df` using `Country` on the x-axis and `GDP` on the y-axis. 
Remember to `plt.show()` your chart!
"""

f = plt.figure(figsize=(12,7))
sns.barplot(data=df, x='Country', y='GDP')
plt.show()

"""B) Create a bar chart using the data in `df` with `Country` on the x-axis and `LEABY` on the y-axis.
Remember to `plt.show()` your chart!
"""

f = plt.figure(figsize=(12,7))
sns.barplot(data=df, x='Country', y='LEABY')
plt.show()

"""What do you notice about the two bar charts? Do they look similar?"""

#No, they do not look similar.
#There is a huge difference between GDP of these countries but slightly difference in LEAPY beside Zimbabwe.

"""## Step 6. Violin Plots To Compare Life Expectancy Distributions

Another way to compare two datasets is to visualize the distributions of each and to look for patterns in the shapes.

We have added the code to instantiate a figure with the correct dimmensions to observe detail. 
1. Create an `sns.violinplot()` for the dataframe `df` and map `Country` and `LEABY` as its respective `x` and `y` axes. 
2. Be sure to show your plot
"""

fig = plt.subplots(figsize=(15, 10)) 
sns.violinplot(data=df, x = 'Country', y='LEABY')
plt.show()

"""What do you notice about this distribution? Which country's life expactancy has changed the most?"""

#The life expectancy of the zimbabwe is changed most and others looks quite similar.

"""## Step 7. Bar Plots Of GDP and Life Expectancy over time

We want to compare the GDPs of the countries over time, in order to get a sense of the relationship between GDP and life expectancy. 

First, can plot the progession of GDP's over the years by country in a barplot using Seaborn.
We have set up a figure with the correct dimensions for your plot. Under that declaration:
1. Save `sns.barplot()` to a variable named `ax`
2. Chart `Country` on the x axis, and `GDP` on the `Y` axis on the barplot. Hint: `ax = sns.barplot(x="Country", y="GDP")`
3. Use the `Year` as a `hue` to differentiate the 15 years in our data. Hint: `ax = sns.barplot(x="Country", y="GDP", hue="Year", data=df)`
4. Since the names of the countries are long, let's rotate their label by 90 degrees so that they are legible. Use `plt.xticks(rotation=90)`
5. Since our GDP is in trillions of US dollars, make sure your Y label reflects that by changing it to `"GDP in Trillions of U.S. Dollars"`. Hint: `plt.ylabel("GDP in Trillions of U.S. Dollars")`
6. Be sure to show your plot.
"""

f, ax = plt.subplots(figsize=(10, 15)) 
sns.barplot(data=df, x='Country',y="GDP", hue='Year')
plt.ylabel("GDP in Trillions of U.S Dollars")
plt.xticks(rotation=90)
plt.show()

"""Now that we have plotted a barplot that clusters GDP over time by Country, let's do the same for Life Expectancy.

The code will essentially be the same as above! The beauty of Seaborn relies in its flexibility and extensibility. Paste the code from above in the cell bellow, and: 
1. Change your `y` value to `LEABY` in order to plot life expectancy instead of GDP. Hint: `ax = sns.barplot(x="Country", y="LEABY", hue="Year", data=df)`
2. Tweak the name of your `ylabel` to reflect this change, by making the label `"Life expectancy at birth in years"` Hint: `ax.set(ylabel="Life expectancy at birth in years")`
"""

f, ax = plt.subplots(figsize=(10, 15)) 
sns.barplot(data=df, x='Country',y="LEABY", hue='Year')
ax.set(ylabel="Life expectancy at birth in years")
plt.show()

"""What are your first impressions looking at the visualized data?

- Which countries' bars changes the most?
- What years are there the biggest changes in the data?
- Which country has had the least change in GDP over time? 
- How do countries compare to one another?
- Now that you can see the both bar charts, what do you think about the relationship between GDP and life expectancy?
- Can you think of any reasons that the data looks like this for particular countries?
"""

# Which countries' bars changes the most?
# Zimbabwe is the most notable althought China and Chile have significant changes too

# What years are there the biggest changes in the data?
# Probably from early 2000 to 2008 for most contries, however Zimbabwe showed a decrease in LEABY, bouncing back from
# 2005 on. It's LEABY and GDP are also considerably different from the rest of the countries studied.

# Which country has had the least change in GDP over time?
# Chile (since Zimbabwe doesn't even show up in the chart)

# How do countries compare to one another?
# It is very clear which are first world countries, with a strong economy (Germany, USA) vs the ones with a 
# rising economy (China) and third world countries (Chile, Mexico and Zimbabwe).

# Now that you can see the both bar charts, what do you think about the relationship between GDP and life expectancy?
# GDP doesn't seem to be a good indicator to predict LEABY, at least after a certain point since Chile and USA share
# similar LEABYs with VERY different GDPs. It is notable however that Zimbabwe has a very small GDP and also a very 
# low LEABY, although this could be related to other causes than just a low GDP.

# Can you think of any reasons that the data looks like this for particular countries?
# GDP has been used by many authors in the past to explain a country's economic health, however GDP does not exactly 
# reflect differences in the cost of living and the inflation rates of the countries; 
# therefore using a basis of GDP per capita at purchasing power parity (PPP) is arguably more useful when 
# comparing living standards between nations (like LEABY), while nominal GDP is more useful comparing national 
# economies on the international market.

"""Note: You've mapped two bar plots showcasing a variable over time by country, however, bar charts are not traditionally used for this purpose. In fact, a great way to visualize a variable over time is by using a line plot. While the bar charts tell us some information, the data would be better illustrated on a line plot.  We will complete this in steps 9 and 10, for now let's switch gears and create another type of chart.

## Step 8. Scatter Plots of GDP and Life Expectancy Data

To create a visualization that will make it easier to see the possible correlation between GDP and life expectancy, you can plot each set of data on its own subplot, on a shared figure.

To create multiple plots for comparison, Seaborn has a special (function)[https://seaborn.pydata.org/generated/seaborn.FacetGrid.html] called `FacetGrid`. A FacetGrid takes in a function and creates an individual graph for which you specify the arguments!
    
Since this may be the first time you've learned about FacetGrid, we have prepped a fill in the blank code snippet below. 
Here are the instructors to fill in the blanks from the commented word bank:

1. In this graph, we want GDP on the X axis and Life Expectancy on the Y axis.
2. We want the columns to be split up for every Year in the data
3. We want the data points to be differentiated (hue) by Country.
4. We want to use a Matplotlib scatter plot to visualize the different graphs


Be sure to show your plot!
"""

# WORDBANK:
# "Year"
# "Country" 
# "GDP" 
# "LEABY" 
# plt.scatter


# Uncomment the code below and fill in the blanks
g = sns.FacetGrid(df, col='Year', hue='Country', col_wrap=4, height=4)
g = (g.map(plt.scatter, 'GDP', 'LEABY', edgecolor="w").add_legend()).set_axis_labels('GDP (trillion USD)', 'Life Expectancy (years)')
plt.title('Evolution of LEABY vs GDP by Year')
plt.savefig("Evolution of LEABY vs GDP by Year.png")
plt.show()

"""+ Which country moves the most along the X axis over the years?
+ Which country moves the most along the Y axis over the years?
+ Is this surprising?
+ Do you think these scatter plots are easy to read? Maybe there's a way to plot that!
"""

# Which country moves the most along the X axis over the years?
# China, as it is an emerging economy and USA

# Which country moves the most along the Y axis over the years?
# Zymbabwe as its LEABY experiences the most change of all

# Do you think these scatter plots are easy to read? Maybe there's a way to plot that!
# Absolutely not, they actually suck

"""## Step 9. Line Plots for Life Expectancy

In the scatter plot grid above, it was hard to isolate the change for GDP and Life expectancy over time. 
It would be better illustrated with a line graph for each GDP and Life Expectancy by country. 

FacetGrid also allows you to do that! Instead of passing in `plt.scatter` as your Matplotlib function, you would have to pass in `plt.plot` to see a line graph. A few other things have to change as well. So we have created a different codesnippets with fill in the blanks.  that makes use of a line chart, and we will make two seperate FacetGrids for both GDP and Life Expectancy separately.

Here are the instructors to fill in the blanks from the commented word bank:

1. In this graph, we want Years on the X axis and Life Expectancy on the Y axis.
2. We want the columns to be split up by Country
3. We want to use a Matplotlib line plot to visualize the different graphs


Be sure to show your plot!
"""

# WORDBANK:
# plt.plot
# "LEABY"
# "Year"
# "Country"


# Uncomment the code below and fill in the blanks
g3 = sns.FacetGrid(df, col="Country", col_wrap=3, height=4)
g3 = (g3.map(plt.plot, "Year", "LEABY", marker='.').add_legend()).set_axis_labels('Year', 'Life Expectancy (years)')

# Made some changes to the x-ticks to improve readability:
# - Updated x-ticks so you can see each year in the x axis
g3.set(xticks=df.Year[0:16])
# - Edited x-tick labels so you can see every year
years = range(2000, 2016)
g3.set(xticklabels=years)
# - Rotated labels to avoid crowding
g3.set_xticklabels(rotation=45)

plt.title('Evolution of LEABY by Year and Country')
plt.savefig("Evolution of LEABY by Year and Country.png")

plt.show()

"""What are your first impressions looking at the visualized data?

- Which countries' line changes the most?
- What years are there the biggest changes in the data?
- Which country has had the least change in life expectancy over time? 
- Can you think of any reasons that the data looks like this for particular countries?
"""

#Which countries' line changes the most? 
#Zimbabwe's 
#What years are there the biggest changes in the data? 
#2007 to 2011 
#Which country has had the least change in life expectancy over time?
# Mexico 
#Can you think of any reasons that the data looks like this for particular countries?
'''Over the recent decades, significant inconsistencies have been witnessed in Zimbabwe’s life expectancy 
patterns. While most countries in the world recorded upward trends in average life expectancy, Zimbabwe
recorded erratic trends in life expectancy. In the two decades leading to 2007, life expectancy in Zimbabwe
dropped significantly as a result of several factors. Such factors include the blowout of HIV, AIDS and
other deadly diseases (Griffith, 2001 and Chapman, et al., 2006), deteriorating economic activity and lack of 
access to medical facilities (Yikoniko, 2012), as well as the viral spread of poverty in the country as 
explained in Mahfuz (2008). Life expectancy in Zimbabwe dropped to the lowest average over the decades in the
2000 to 2009 decade where Zimbabweans were on average expected to live for up to 45.2 years.
This histrionic decline in life expectancy may be attributed to the deterioration of the standard of living 
which was a result of a decline in the country’s economic activities. The Zimbabwean economy experienced a 
meltdown during this period. Hyperinflation coupled with poor economic management policies brought the 
Zimbabwean economy to near standstill. As a result of this, there were basic food shortages and most retail 
commodities were found only in the streets. The socio-economic sector was also heavily affected by the
adverse economic conditions in Zimbabwe. There was a huge decline in the education standards and the health 
sector nearly collapsed. This contributed significantly to the declining life expectancy. However, between 
2007 and 2012, life expectancy in Zimbabwe increased to an average of about 53.9 years. On average, 
Zimbabweans now lived about 8 years longer in this decade relative to the previous decade. This improvement 
could be credited to the formation of a Government of National Unity (GNU) formed between the Zimbabwe 
African National Union-Patriotic Front (ZANU PF) and the two factions of the Movement for Democratic Change 
(MDC). The coalition of these political parties to form a government of national unity brought stability and
 some sense of hope in Zimbabwe. The use of multiple foreign currencies, to a larger extent, also 
 resuscitated the economy which was on the brink of total collapse at the time of the formation of the unity 
 government. Accordingly, state hospitals, shops and other businesses reopened and basic food staffs were back on the market.
This improved the overall mortality of the Zimbabwean population. 
Source: https://www.researchgate.net/publication/297750732_Life_Expectancy_In_Zimbabwe_An_Analysis_Of_Five_Decades'''

"""## Step 10. Line Plots for GDP

Let's recreate the same FacetGrid for GDP now. Instead of Life Expectancy on the Y axis, we now we want GDP.

Once you complete and successfully run the code above, copy and paste it into the cell below. Change the variable for the X axis. Change the color on your own! Be sure to show your plot.
"""

g3 = sns.FacetGrid(df, col="Country", col_wrap=3, height=4)
g3 = (g3.map(plt.plot, "Year", "GDP", marker='.').add_legend()).set_axis_labels('Year', 'GDP')

# Made some changes to the x-ticks to improve readability:
# - Updated x-ticks so you can see each year in the x axis
g3.set(xticks=df.Year[0:16])
# - Edited x-tick labels so you can see every year
years = range(2000, 2016)
g3.set(xticklabels=years)
# - Rotated labels to avoid crowding
g3.set_xticklabels(rotation=45)
plt.show()

"""Which countries have the highest and lowest GDP?"""

# Germany, China and USA (note that china starts at a much lower GDP than it finishes,
#due to its exponential economic growth over the last two decades) 
#Lowest: - Zimbabwe (by far), Chile and Mexico

"""Which countries have the highest and lowest life expectancy?"""

#Highest: - Germany, Chile, USA and Mexico, all followed closely by China 
#Lowest: - Zimbabwe (by far)

"""## Step 11 Researching Data Context

Based on the visualization, choose one part the data to research a little further so you can add some real world context to the visualization. You can choose anything you like, or use the example question below.

What happened in China between in the past 10 years that increased the GDP so drastically?
"""

''' China has experienced exponential growth over the past few decades, breaking the barriers of a 
centrally-planned closed economy to evolve into a manufacturing and exporting hub of the world. 
China is often referred to as the "world's factory," given its huge manufacturing and export base. 
However, over the years, the role of services has gradually increased and that of manufacturing as a 
contributor to GDP has declined relatively. Back in 1980, China was the seventh-largest economy, 
with a GDP of $305.35 billion, while the size of the U.S. then was $2.86 trillion.
Since it initiated market reforms in 1978, the Asian giant has seen an economic growth averaging 10% annually.
In recent years, the pace of growth has slowed, although it remains high in comparison to its peer nations.'''

"""## Step 12 Create Blog Post

Use the content you have created in this Jupyter notebook to create a blog post reflecting on this data.
Include the following visuals in your blogpost:

1. The violin plot of the life expectancy distribution by country
2. The facet grid of scatter graphs mapping GDP as a function Life Expectancy by country
3. The facet grid of line graphs mapping GDP by country
4. The facet grid of line graphs mapping Life Expectancy by country


We encourage you to spend some time customizing the color and style of your plots! Remember to use `plt.savefig("filename.png")` to save your figures as a `.png` file.

When authoring your blog post, here are a few guiding questions to guide your research and writing:
+ How do you think the histories and the cultural values of each country relate to its GDP and life expectancy?
+ What would have helped make the project data more reliable? What were the limitations of the dataset?
+ Which graphs better illustrate different relationships??
"""

